export const reducerCases={
    SET_TOKEN:"SET_TOKEN",
    SET_PLAYLISTS:'SET_PLAYLISTS',
    SET_USER:"SET_USER",
    SET_RECENTLY_PLAYED:'SET_RECENTLY_PLAYED',
    SET_PLAYING:'SET_PLAYING',
    SET_PLAYER_STATE: "SET_PLAYER_STATE",
    SET_VIEW_PLAYLISTS: "SET_VIEW_PLAYLISTS",
    SET_CAT:'SET_CAT',
    SEARCH:'SEARCH'
}